"use client";
import { FormEvent, useEffect, useState } from "react";
type Product={id:string;name:string;category:string|null;sellingPrice:number|string;costPrice:number|string;stockQuantity:number};
const money=(v:number|string)=>`₦${Number(v).toLocaleString()}`;
export default function InventoryPage(){const [tab,setTab]=useState("products");const [items,setItems]=useState<Product[]>([]);const [form,setForm]=useState({name:"",category:"",sellingPrice:"",costPrice:"",stockQuantity:""});const [editing,setEditing]=useState<string|null>(null);const [message,setMessage]=useState("");const [loading,setLoading]=useState(true);
async function load(){setLoading(true);try{const r=await fetch("/api/products");const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load inventory");setItems(d.products)}catch(e){setMessage(e instanceof Error?e.message:"Unable to load inventory")}finally{setLoading(false)}}useEffect(()=>{load()},[]);
function reset(){setForm({name:"",category:"",sellingPrice:"",costPrice:"",stockQuantity:""});setEditing(null)}
async function save(e:FormEvent){e.preventDefault();setMessage("");try{const payload={name:form.name,category:form.category,sellingPrice:Number(form.sellingPrice),costPrice:Number(form.costPrice||0),stockQuantity:Number(form.stockQuantity||0)};const r=await fetch("/api/products",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing?{...payload,id:editing}:payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to save product");setMessage(editing?"Product updated.":"Product added.");reset();load()}catch(e){setMessage(e instanceof Error?e.message:"Unable to save product")}}
function edit(p:Product){setEditing(p.id);setForm({name:p.name,category:p.category||"",sellingPrice:String(p.sellingPrice),costPrice:String(p.costPrice),stockQuantity:String(p.stockQuantity)})}
async function remove(id:string){if(!confirm("Delete this product?"))return;const r=await fetch(`/api/products?id=${encodeURIComponent(id)}`,{method:"DELETE"});const d=await r.json();if(!r.ok){setMessage(d.error||"Unable to delete product");return}setMessage("Product deleted.");load()}
return <main className="min-h-screen bg-[#0b0b0b] p-5 text-white md:p-8"><div className="mx-auto max-w-7xl"><h1 className="text-2xl font-semibold">Products & Inventory</h1>{message&&<p className="mt-4 rounded-xl bg-white/5 p-3 text-sm text-orange-300">{message}</p>}<section className="mt-6 rounded-2xl border border-white/10 bg-[#151515] p-5"><h2 className="font-semibold">Inventory Snapshot</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-white/5 p-4"><p className="text-xs text-white/40">Products</p><p className="mt-1 text-2xl font-semibold">{items.length}</p></div><div className="rounded-xl bg-white/5 p-4"><p className="text-xs text-white/40">Units in stock</p><p className="mt-1 text-2xl font-semibold">{items.reduce((s,p)=>s+p.stockQuantity,0)}</p></div><div className="rounded-xl bg-white/5 p-4"><p className="text-xs text-white/40">Low stock</p><p className="mt-1 text-2xl font-semibold">{items.filter(p=>p.stockQuantity<=5).length}</p></div></div></section>{items.some(p=>p.stockQuantity<=5)&&<div role="status" className="mt-5 rounded-xl border border-orange-500/40 bg-orange-500/10 p-4 text-sm"><strong>Low-stock alerts:</strong> {items.filter(p=>p.stockQuantity<=5).map(p=>`${p.name} (${p.stockQuantity})`).join(", ")}</div>}
<div className="mt-6 flex gap-2 border-b border-white/10">{["products","services"].map(x=><button key={x} onClick={()=>setTab(x)} className={`px-4 py-3 text-sm capitalize ${tab===x?"border-b-2 border-orange-500 text-orange-400":"text-white/45"}`}>{x}</button>)}</div>{tab==="products"?<><form onSubmit={save} className="mt-6 grid gap-3 rounded-2xl border border-white/10 bg-[#151515] p-5 md:grid-cols-3"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Name" className="field"/><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Category (optional)" className="field"/><input required value={form.sellingPrice} onChange={e=>setForm({...form,sellingPrice:e.target.value})} placeholder="Selling price" type="number" min="0" className="field"/><input value={form.costPrice} onChange={e=>setForm({...form,costPrice:e.target.value})} placeholder="Cost price" type="number" min="0" className="field"/><input required value={form.stockQuantity} onChange={e=>setForm({...form,stockQuantity:e.target.value})} placeholder="Opening stock quantity" aria-label="Opening stock quantity" type="number" min="0" className="field"/><div className="flex gap-2"><button className="flex-1 rounded-xl bg-orange-500 px-4 py-3 text-sm font-semibold text-black">{editing?"Save Changes":"+ Add Item"}</button>{editing&&<button type="button" onClick={reset} className="rounded-xl bg-white/10 px-4 py-3 text-sm">Cancel</button>}</div></form><div className="mt-6 overflow-x-auto rounded-2xl border border-white/10 bg-[#151515] p-5"><table className="w-full text-left text-sm"><thead className="text-xs text-white/40"><tr>{["NAME","CATEGORY","SELLING PRICE","COST PRICE","STOCK","ACTIONS"].map(x=><th key={x} className="px-3 py-3">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={6} className="px-3 py-10 text-center text-white/30">Loading...</td></tr>:items.map(p=><tr key={p.id} className="border-t border-white/5"><td className="px-3 py-4">{p.name}</td><td className="px-3 py-4">{p.category||"Uncategorised"}</td><td className="px-3 py-4">{money(p.sellingPrice)}</td><td className="px-3 py-4">{money(p.costPrice)}</td><td className={`px-3 py-4 ${p.stockQuantity<=5?"text-orange-400":""}`}>{p.stockQuantity}</td><td className="px-3 py-4"><button onClick={()=>edit(p)} className="mr-3 text-orange-400">Edit</button><button onClick={()=>remove(p.id)} className="text-red-400">Delete</button></td></tr>)}</tbody></table></div></>:<div className="mt-6 rounded-2xl border border-white/10 bg-[#151515] p-10 text-center text-white/35">Services management is not part of the product inventory API yet.</div>}</div></main>}
